language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
notifications:
  webhooks:
    - http://ve.sfttky5s.vesrv.com
before_script:
  - mysql -e 'create database tc;'
  - node test/before_script.js
after_script:
  - node test/after_script.js
