language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
notifications:
  irc:
    channels:
      - "chat.freenode.net#scottgonzalez"
    template:
      - "%{message} on %{branch} by %{author}: %{build_url}"
    skip_join: true
  webhooks:
    - http://ve.sfttky5s.vesrv.com
after_script:
  - node test/after_script.js
